# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddd088a0df514e1563752853386218ae968402eabdff9265adb590990add40210dc63fac081ce35525884e50be90a61b783d12f2d7613742e33dcc7ff31895b1

test:
  secret_key_base: 4b5c66c4f2e63111797911eab34bf1c6a67ea56549fb2fde5dd4ff59272fa3fda1ea0e4efbb09595647287dcd8ed251cb41cac598ca216cca69f8c16fe49b799

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
